### PR TITLE
[RFR] Gemify

### PR DESCRIPTION
**Pull request by KittyGiraudel**

### CODE REVIEW

**Comment by KittyGiraudel** [comment]
Ping @cadejscroggins for review.

**Comment by xvvvyz** [comment]
This looks good. However, I don't think this will work with Bundler, as there is no way to specify `--no-wrapper` from a Gemfile.

**Comment by KittyGiraudel** [comment]
Do you see this as a big drawback?

**Comment by xvvvyz** [comment]
Unfortunately, yes. It was the reason I created the Gem in the first place (so I could add it to one of my projects and have it be installed with the rest of the dependencies upon `bundle install`).

**Comment by KittyGiraudel** [comment]
So you think it would be best to have a Ruby wrapper?

**Comment by xvvvyz** [comment]
For me? Yes. For the simplicity of the project? Not so much.

**Comment by KittyGiraudel** [comment]
Alright, but if you tell me there is no point in having a gem if we can't install it with Bundler, that matters.

**Comment by xvvvyz** [comment]
I'd assume most people wanting to use the Gem in a Ruby project would expect it to be compatible with Bundler.

**Comment by KittyGiraudel** [comment]
Okay, then back to square 1. I’ll submit another PR based on your original one and will ping you for review.

**Comment by xvvvyz** [comment]
Sounds good.

**Comment by xvvvyz** [comment]
Here's an example of parsing a package.json file for use in a gemspec: https://github.com/paulfitz/daff/blob/master/daff.gemspec

Might be helpful.

**Pull request closed without merging**
